### ISSUE TITLE
Lunch error while using Ros2 Humble

### ISSUE THREAD

**Issue by asadwadood** [MISTLab/Swarm-SLAM#29]
hello,
i am using Swarm-SLam. when i tried to run on Ros2 Humble ,i can build it. but getting error while launching it.

slam) a@Asad:~/Swarm-SLAM$ ros2 launch cslam_experiments graco_lidar.launch.py 
[INFO] [launch]: All log files can be found below /home/a/.ros/log/2024-03-07-16-46-10-122207-Asad-78396
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): "package 'rtabmap_odom' not found, searching: ['/home/a/Swarm-SLAM/install/cslam_experiments', '/home/a/Swarm-SLAM/install/cslam', '/home/a/Swarm-SLAM/install/cslam_common_interfaces', '/opt/ros/humble']"
[INFO] [static_transform_publisher-1]: process started with pid [78397]
[INFO] [static_transform_publisher-2]: process started with pid [78399]
[INFO] [loop_closure_detection_node.py-3]: process started with pid [78419]
[INFO] [lidar_handler_node.py-4]: process started with pid [78421]
[INFO] [pose_graph_manager-5]: process started with pid [78423]
[INFO] [static_transform_publisher-2]: sending signal 'SIGINT' to process[static_transform_publisher-2]
[INFO] [static_transform_publisher-1]: sending signal 'SIGINT' to process[static_transform_publisher-1]
[static_transform_publisher-1] [WARN] [1709797570.192786070] []: Old-style arguments are deprecated; see --help for new-style arguments
[static_transform_publisher-1] [INFO] [1709797570.203246452] [static_transform_publisher_SNO0Kpo63NvwE0kJ]: Spinning until stopped - publishing transform
[static_transform_publisher-1] translation: ('0.000000', '0.000000', '0.000000')
[static_transform_publisher-1] rotation: ('0.000000', '0.000000', '0.000000', '1.000000')
[static_transform_publisher-1] from 'velodyne' to 'base_link'
[static_transform_publisher-2] [WARN] [1709797570.192773967] []: Old-style arguments are deprecated; see --help for new-style arguments
[static_transform_publisher-2] [INFO] [1709797570.205952163] [static_transform_publisher_AYSJuVVWtWZbvo9U]: Spinning until stopped - publishing transform
[static_transform_publisher-2] translation: ('-0.011920', '-0.019700', '0.122600')
[static_transform_publisher-2] rotation: ('0.000000', '0.000000', '0.000000', '1.000000')
[static_transform_publisher-2] from 'velodyne' to 'gnss'
[INFO] [pose_graph_manager-5]: sending signal 'SIGINT' to process[pose_graph_manager-5]
[INFO] [lidar_handler_node.py-4]: sending signal 'SIGINT' to process[lidar_handler_node.py-4]
[INFO] [loop_closure_detection_node.py-3]: sending signal 'SIGINT' to process[loop_closure_detection_node.py-3]
[static_transform_publisher-2] [INFO] [1709797570.245665519] [rclcpp]: signal_handler(signum=2)
[static_transform_publisher-1] [INFO] [1709797570.246285255] [rclcpp]: signal_handler(signum=2)
[lidar_handler_node.py-4] Traceback (most recent call last):
[lidar_handler_node.py-4]   File "/home/a/miniconda3/envs/cslam/lib/python3.10/site-packages/numpy/core/__init__.py", line 24, in <module>
[lidar_handler_node.py-4]     from . import multiarray
[lidar_handler_node.py-4]   File "/home/a/miniconda3/envs/cslam/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
[pose_graph_manager-5] [INFO] [1709797570.250156279] [rclcpp]: signal_handler(signum=2)
[lidar_handler_node.py-4]     from . import overrides
[lidar_handler_node.py-4]   File "/home/a/miniconda3/envs/cslam/lib/python3.10/site-packages/numpy/core/overrides.py", line 8, in <module>
[lidar_handler_node.py-4]     from numpy.core._multiarray_umath import (
[lidar_handler_node.py-4] ImportError: PyCapsule_Import could not import module "datetime"
[lidar_handler_node.py-4] 
[lidar_handler_node.py-4] During handling of the above exception, another exception occurred:
[lidar_handler_node.py-4] 
[lidar_handler_node.py-4] Traceback (most recent call last):
[lidar_handler_node.py-4]   File "/home/a/miniconda3/envs/cslam/lib/python3.10/site-packages/numpy/__init__.py", line 130, in <module>
[lidar_handler_node.py-4]     from numpy.__config__ import show as show_config
[lidar_handler_node.py-4]   File "/home/a/miniconda3/envs/cslam/lib/python3.10/site-packages/numpy/__config__.py", line 4, in <module>
[lidar_handler_node.py-4]     from numpy.core._multiarray_umath import (
[lidar_handler_node.py-4]   File "/home/a/miniconda3/envs/cslam/lib/python3.10/site-packages/numpy/core/__init__.py", line 50, in <module>
[lidar_handler_node.py-4]     raise ImportError(msg)
[lidar_handler_node.py-4] ImportError: 
[lidar_handler_node.py-4] 
[lidar_handler_node.py-4] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
[lidar_handler_node.py-4] 
[lidar_handler_node.py-4] Importing the numpy C-extensions failed. This error can happen for
[lidar_handler_node.py-4] many reasons, often due to issues with your setup or how NumPy was
[lidar_handler_node.py-4] installed.
[lidar_handler_node.py-4] 
[lidar_handler_node.py-4] We have compiled some common reasons and troubleshooting tips at:
[lidar_handler_node.py-4] 
[lidar_handler_node.py-4]     https://numpy.org/devdocs/user/troubleshooting-importerror.html
[lidar_handler_node.py-4] 
[lidar_handler_node.py-4] Please note and check the following:
[lidar_handler_node.py-4] 
[lidar_handler_node.py-4]   * The Python version is: Python3.10 from "/home/a/miniconda3/envs/cslam/bin/python3"
[lidar_handler_node.py-4]   * The NumPy version is: "1.26.4"
[lidar_handler_node.py-4] 
[lidar_handler_node.py-4] and make sure that they are the versions you expect.
[lidar_handler_node.py-4] Please carefully study the documentation linked above for further help.
[lidar_handler_node.py-4] 
[lidar_handler_node.py-4] Original error was: PyCapsule_Import could not import module "datetime"
[lidar_handler_node.py-4] 
[lidar_handler_node.py-4] 
[lidar_handler_node.py-4] The above exception was the direct cause of the following exception:
[lidar_handler_node.py-4] 
[lidar_handler_node.py-4] Traceback (most recent call last):
[lidar_handler_node.py-4]   File "/home/a/Swarm-SLAM/install/cslam/lib/cslam/lidar_handler_node.py", line 2, in <module>
[lidar_handler_node.py-4]     import numpy as np
[lidar_handler_node.py-4]   File "/home/a/miniconda3/envs/cslam/lib/python3.10/site-packages/numpy/__init__.py", line 135, in <module>
[lidar_handler_node.py-4]     raise ImportError(msg) from e
[lidar_handler_node.py-4] ImportError: Error importing numpy: you should not try to import numpy from
[lidar_handler_node.py-4]         its source directory; please exit the numpy source tree, and relaunch
[lidar_handler_node.py-4]         your python interpreter from there.
[pose_graph_manager-5] terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
[pose_graph_manager-5]   what():  could not create subscription: rcl node's context is invalid, at ./src/rcl/node.c:428
[loop_closure_detection_node.py-3] Traceback (most recent call last):
[loop_closure_detection_node.py-3]   File "/home/a/Swarm-SLAM/install/cslam/lib/cslam/loop_closure_detection_node.py", line 5, in <module>
[loop_closure_detection_node.py-3]     import rclpy
[loop_closure_detection_node.py-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 48, in <module>
[loop_closure_detection_node.py-3]     from rclpy.parameter import Parameter
[loop_closure_detection_node.py-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/parameter.py", line 18, in <module>
[loop_closure_detection_node.py-3]     from rcl_interfaces.msg import Parameter as ParameterMsg
[loop_closure_detection_node.py-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rcl_interfaces/msg/__init__.py", line 1, in <module>
[loop_closure_detection_node.py-3]     from rcl_interfaces.msg._floating_point_range import FloatingPointRange  # noqa: F401
[loop_closure_detection_node.py-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rcl_interfaces/msg/_floating_point_range.py", line 12, in <module>
[loop_closure_detection_node.py-3]     import rosidl_parser.definition  # noqa: E402, I100
[loop_closure_detection_node.py-3] KeyboardInterrupt
[ERROR] [loop_closure_detection_node.py-3]: process has died [pid 78419, exit code -2, cmd '/home/a/Swarm-SLAM/install/cslam/lib/cslam/loop_closure_detection_node.py --ros-args -r __node:=cslam_loop_closure_detection -r __ns:=/r0 --params-file /home/a/Swarm-SLAM/install/cslam_experiments/share/cslam_experiments/config/graco_lidar.yaml --params-file /tmp/launch_params_ihvu_x9h'].
[ERROR] [lidar_handler_node.py-4]: process has died [pid 78421, exit code 1, cmd '/home/a/Swarm-SLAM/install/cslam/lib/cslam/lidar_handler_node.py --ros-args -r __node:=cslam_map_manager -r __ns:=/r0 --params-file /home/a/Swarm-SLAM/install/cslam_experiments/share/cslam_experiments/config/graco_lidar.yaml --params-file /tmp/launch_params_ccylq2jj -r /r0/pointcloud:=/points'].
[ERROR] [pose_graph_manager-5]: process has died [pid 78423, exit code -6, cmd '/home/a/Swarm-SLAM/install/cslam/lib/cslam/pose_graph_manager --ros-args -r __node:=cslam_pose_graph_manager -r __ns:=/r0 --params-file /home/a/Swarm-SLAM/install/cslam_experiments/share/cslam_experiments/config/graco_lidar.yaml --params-file /tmp/launch_params_1ic42_ao'].
[INFO] [static_transform_publisher-1]: process has finished cleanly [pid 78397]
[INFO] [static_transform_publisher-2]: process has finished cleanly [pid 78399]

please suggest the solution. thank you
![Screenshot from 2024-03-07 16-51-36](https://github.com/MISTLab/Swarm-SLAM/assets/32166305/77d682ae-0b32-4567-810a-36420d5e4fcd)

**Comment by asadwadood** [comment]
Thank you.  it worked.
